baseURL = "https://m-yoshinaka.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Masato Yoshinaka"
theme = "anatole"

enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true

paginate = 3
summarylength = 10

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]

  title = "Masato Yoshinaka"
  description = "Second-year master’s student in Osaka University"
  author = "Masato Yoshinaka"
  copyright = "2019-2021"
  profilePicture = "images/icon.jpg"
  mainSections = [""]
  customCss = ["css/custom.css"]
  doNotLoadAnimations = true

  singleDateFormat = "2006-01-02"
  indexDateFormat = "2006-01-02"
  listDateFormat = "2006-01-02"

  gtagId = "G-ZLNB31L9E0"

  # Social links
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/m-yoshinaka"

  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:yoshinaka.masato[at]ist.osaka-u.ac.jp"

[menu]

  [[menu.main]]
  name = "ABOUT"
  identifier = "about"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "CONTACT"
  weight = 200
  identifier = "contact"
  url = "/contact"

  [[menu.main]]
  name = "NEWS"
  weight = 300
  identifier = "news"
  url = "/post/"

[Languages]

  [Languages.en]
  title = "Masato Yoshinaka"
  LanguageName = "English"
  contentDir = "content/en"
  weight = 2

  [Languages.ja]
  title = "Masato Yoshinaka"
  LanguageName = "日本語"
  contentDir = "content/ja"
  weight = 1

  [[Languages.ja.menu.main]]
  name = "ABOUT"
  weight = 100
  identifier = "about"
  url = "/ja/"

  [[Languages.ja.menu.main]]
  name = "NEWS"
  weight = 200
  identifier = "news"
  url = "/ja/post/"

  [[Languages.ja.menu.main]]
  name = "CONTACT"
  weight = 300
  identifier = "contact"
  url = "/contact/"
