baseURL = "https://m-yoshinaka.github.io/"
title = "Masato YOSHINAKA"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true

pygmentsStyle = "monokai"

[params]
  footer = "Masato Yoshinaka All Rights Reserved"
  description = "Alumnus of Osaka University"
  avatarURL = "/images/profile.jpg"
  avatarSize = "size-s"
  accentColor = "#81a1c1"
  showPostsOnHomePage = "recent"
  customHeadHTML = """
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-CLZ3G11HP5"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-CLZ3G11HP5');
    </script>
  """

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "Publications"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4


  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/m-yoshinaka"
    weight = 5
