baseURL = "https://m-yoshinaka.github.io/"
languageCode = "ja-jp"
DefaultContentLanguage = "ja-jp"
title = "Website of Masato Yoshinaka"
theme = "anatole"

enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true

paginate = 3
summarylength = 10

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]

  title = "Masato Yoshinaka"
  description = "Second-year master’s student in Osaka University"
  author = "Masato Yoshinaka"
  copyright = "2019-2021"
  profilePicture = "images/icon.jpg"
  mainSections = [""]

  singleDateFormat = "2006-01-02"
  indexDateFormat = "2006-01-02"
  listDateFormat = "January 02, 2006"

  ## Math settings
  [[params.math]]
    enable = false
    use = "katex"

  ## Social links
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/m-yoshinaka"

  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:yoshinaka.masato[at]ist.osaka-u.ac.jp"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "English"
  weight = 300
  identifier = "english"
  url = "/en/"
